In [ ]:
# all checking courses and courses descriptions include 4 parts:

# 1st: all courses and courses descriptions under Thayer School of Engineering
# 2nd: all courses and courses descriptions under Tuck School of Business
# 3rd: all courses and courses descriptions under 'schools of arts and sciences' and 'Geisel School of Medicine matched programs', already generated and saved under 'dartmouth_matched_ungergrad_med_department.csv'
# 4th: all courses and courses descriptions under Guarini School of Graduate and Advanced Studies

In [ ]:
# combine all courses together preparing to against selected D.S job title 
# courses files include 
# 1: thayer school of engineering file - "dartmouth_engineering_courses.csv"
# 2: Tuck School of Business file - "tuck_school_courses_total.csv"
# 3: schools of arts and sciences -'arts_science_grad_courses.csv'
# 4: Geisel School of Medicine courses - 'med_courses.csv'
# 5 Guarini School of Graduate and Advanced Studies: it's not an independent school and all its courses are open from other 4 schools, in order to avoid redundant collections and repetitive work, we do not collect courses from this school

In [1]:
# dartmouth_engineering_courses.csv
import pandas as pd
df_loaded_engineering = pd.read_csv('dartmouth_engineering_courses.csv', header = None, names = ['course_code', 'course_name', 'course_description', "course_url"])

In [2]:
df_loaded_engineering

,course_code,course_name,course_description,course_url
0,ENGS 1.01,Mathematical Concepts in Engineering,This course introduces prospective engineering...,https://engineering.dartmouth.edu/courses/unde...
1,ENGS 2,"Integrated Design: Engineering, Architecture, ...",An introduction to the integrated design of st...,https://engineering.dartmouth.edu/courses/unde...
2,ENGS 3,Materials: The Substance of Civilization,"With the exception of ideas and emotions, mate...",https://engineering.dartmouth.edu/courses/unde...
3,ENGS 3.10,Elementary Oceanography,Oceanography is one of the studies in which na...,https://engineering.dartmouth.edu/courses/unde...
4,ENGS 4,Technology of Cyberspace,This course will cover some basic concepts und...,https://engineering.dartmouth.edu/courses/unde...
...,...,...,...,...
264,ENGG 419,Deep Learning,Although there are many approaches to machine ...,https://engineering.dartmouth.edu/courses/grad...
265,ENGG 462,Embedded Systems,This is a graduate-level course covering the d...,https://engineering.dartmouth.edu/courses/grad...
266,ENGG 463,Advanced FPGA Design,This graduate-level course builds on foundatio...,https://engineering.dartmouth.edu/courses/grad...
267,ENGG 499,Smart Sensors,Design methodologies of mobile sensors and sys...,https://engineering.dartmouth.edu/courses/grad...
268,ENGG 700,Responsible & Ethical Conduct of Research,NaN,https://engineering.dartmouth.edu/courses/grad...

In [3]:
# tuck_school_courses_total.csv
import pandas as pd
df_loaded_tuck = pd.read_csv('tuck_school_courses_total.csv', header = None, names = ['course_code','course_name', 'course_description', 'course_url'])

In [4]:
df_loaded_tuck

,course_code,course_name,course_description,course_url
0,NaN,Analytics I,This two-course sequence introduces analytic m...,https://tuck.dartmouth.edu/mba/academic-experi...
1,NaN,Analytics II,The objective of Analytics 2 is to provide you...,https://tuck.dartmouth.edu/mba/academic-experi...
2,NaN,Capital Markets,This course provides a detailed overview of th...,https://tuck.dartmouth.edu/mba/academic-experi...
3,NaN,Corporate Finance,This course discusses basic principles of corp...,https://tuck.dartmouth.edu/mba/academic-experi...
4,NaN,Strategy,This course offers the “essential” toolkit of ...,https://tuck.dartmouth.edu/mba/academic-experi...
...,...,...,...,...
116,NaN,Structuring Mergers and Acquisitions (SMA),This is a minicourse on corporate mergers and ...,https://tuck.dartmouth.edu/mba/academic-experi...
117,NaN,Supply Chain Management (SCHM),A supply chain is comprised of all parties inv...,https://tuck.dartmouth.edu/mba/academic-experi...
118,NaN,VBA Programming (VBAP),This minicourse teaches the fundamentals of co...,https://tuck.dartmouth.edu/mba/academic-experi...
119,NaN,Wicked Societal Challenges (WICKD),Much like the times when Dickens wrote of the ...,https://tuck.dartmouth.edu/mba/academic-experi...
120,NaN,Field Study in Business (FSB),The purpose of this course is to provide stude...,https://tuck.dartmouth.edu/mba/academic-experi...

In [5]:
# schools of arts and sciences - 'arts_science_grad_courses.csv'
import pandas as pd
df_loaded_arts_sciences = pd.read_csv('arts_science_grad_courses.csv', header = None, names = ['course_code','course_name', 'course_description', 'course_url'])

In [6]:
df_loaded_arts_sciences

,course_code,course_name,course_description,course_url
0,103.0,The Molecular Mechanisms of Cellular Responses,"Together with Microbiology 104, this course co...",https://dartmouth.smartcatalogiq.com/en/curren...
1,119.0,Design and Development of Scientific Proposals,This graduate seminar and practicum focuses on...,https://dartmouth.smartcatalogiq.com/en/curren...
2,120.0,Advanced Population Ecology,Described underBIOL 51. Offered in alternate y...,https://dartmouth.smartcatalogiq.com/en/curren...
3,123.0,Advanced Community Ecology,Described underBIOL 58. Offered in alternate y...,https://dartmouth.smartcatalogiq.com/en/curren...
4,125.0,The Nature and Practice of Science,This course compares and contrasts the nature ...,https://dartmouth.smartcatalogiq.com/en/curren...
...,...,...,...,...
401,261.0,Cancer Biology,All graduate students are required to enroll i...,https://dartmouth.smartcatalogiq.com/en/curren...
402,271.0,Graduate Research Colloquium: Chromatin Structure,All graduate students are required to enroll i...,https://dartmouth.smartcatalogiq.com/en/curren...
403,297.0,Graduate Research in Genetics A,"An original individual, experimental, or theor...",https://dartmouth.smartcatalogiq.com/en/curren...
404,298.0,Graduate Research in Genetics B,"An original individual, experimental, or theor...",https://dartmouth.smartcatalogiq.com/en/curren...
405,299.0,Graduate Research in Genetics C,"An original individual, experimental, or theor...",https://dartmouth.smartcatalogiq.com/en/curren...

In [7]:
# Geisel School of Medicine courses - 'med_courses.csv'

import pandas as pd
df_loaded_med_courses= pd.read_csv('med_courses.csv', names = ['course_code','course_name', 'course_description', 'course_url'], header = None)

In [8]:
df_loaded_med_courses

,course_code,course_name,course_description,course_url
0,HSE 700,Responsible and Ethical Conduct of Research,QBS 700 is a required course for all Quantitat...,https://dartmouth.smartcatalogiq.com/current/o...
1,HSE 101,Foundations of Programming,This course is designed for graduate students ...,https://dartmouth.smartcatalogiq.com/en/curren...
2,HSE 101,Intermediate Programming for Data Scientists,Elevate your programming skills and make your ...,https://dartmouth.smartcatalogiq.com/current/o...
3,HSE 103,Foundations of Data Sciences,Strong programming and mathematics skills are ...,https://dartmouth.smartcatalogiq.com/en/curren...
4,HSE 108,Machine Learning,This course provides a comprehensive introduct...,https://dartmouth.smartcatalogiq.com/en/curren...
...,...,...,...,...
173,NaN,"HCDS MOC Managing People, Organizations and Ch...","Today, many organizations confront situations ...",https://dartmouth.smartcatalogiq.com/en/curren...
174,NaN,HCDS PHPC Population Health and Preventive Care,"In this course, students will learn about the ...",https://dartmouth.smartcatalogiq.com/en/curren...
175,NaN,HCDS PLS Personal Leadership,The focus of the course is concrete — building...,https://dartmouth.smartcatalogiq.com/en/curren...
176,NaN,HCDS SPE Specialty Topics in Health Care Delivery,Integrative Experiences in Health Care Deliver...,https://dartmouth.smartcatalogiq.com/en/curren...
177,NaN,HCDS STRAT Strategy for Health Care Organizations,This course focuses on the effective formulati...,https://dartmouth.smartcatalogiq.com/en/curren...

In [16]:
# set all above courses data frame together

df_loaded_courses= pd.concat([df_loaded_engineering, df_loaded_tuck, df_loaded_arts_sciences, df_loaded_med_courses], ignore_index = True)

In [17]:
len(df_loaded_courses)

974

In [18]:
df_loaded_courses

,course_code,course_name,course_description,course_url
0,ENGS 1.01,Mathematical Concepts in Engineering,This course introduces prospective engineering...,https://engineering.dartmouth.edu/courses/unde...
1,ENGS 2,"Integrated Design: Engineering, Architecture, ...",An introduction to the integrated design of st...,https://engineering.dartmouth.edu/courses/unde...
2,ENGS 3,Materials: The Substance of Civilization,"With the exception of ideas and emotions, mate...",https://engineering.dartmouth.edu/courses/unde...
3,ENGS 3.10,Elementary Oceanography,Oceanography is one of the studies in which na...,https://engineering.dartmouth.edu/courses/unde...
4,ENGS 4,Technology of Cyberspace,This course will cover some basic concepts und...,https://engineering.dartmouth.edu/courses/unde...
...,...,...,...,...
969,NaN,"HCDS MOC Managing People, Organizations and Ch...","Today, many organizations confront situations ...",https://dartmouth.smartcatalogiq.com/en/curren...
970,NaN,HCDS PHPC Population Health and Preventive Care,"In this course, students will learn about the ...",https://dartmouth.smartcatalogiq.com/en/curren...
971,NaN,HCDS PLS Personal Leadership,The focus of the course is concrete — building...,https://dartmouth.smartcatalogiq.com/en/curren...
972,NaN,HCDS SPE Specialty Topics in Health Care Delivery,Integrative Experiences in Health Care Deliver...,https://dartmouth.smartcatalogiq.com/en/curren...
973,NaN,HCDS STRAT Strategy for Health Care Organizations,This course focuses on the effective formulati...,https://dartmouth.smartcatalogiq.com/en/curren...

In [19]:
df_loaded_courses = df_loaded_courses.to_csv('all_courses.csv',index=False, header=True)