In [ ]:
# all checking courses and courses descriptions include 4 parts:

# 1st: all courses and courses descriptions under Thayer School of Engineering
# 2nd: all courses and courses descriptions under Tuck School of Business
# 3rd: all courses and courses descriptions under 'schools of arts and sciences' and 'Geisel School of Medicine matched programs', already generated and saved under 'dartmouth_matched_ungergrad_med_department.csv'
# 4th: all courses and courses descriptions under Guarini School of Graduate and Advanced Studies

In [1]:
# dartmouth_engineering_courses.csv
import pandas as pd
df_loaded_engineering = pd.read_csv('dartmouth_engineering_courses.csv', header = None, names = ['course_code', 'course_name', 'course_description', "course_url"])

In [2]:
df_loaded_engineering

,course_code,course_name,course_description,course_url
0,ENGS 1.01,Mathematical Concepts in Engineering,This course introduces prospective engineering...,https://engineering.dartmouth.edu/courses/unde...
1,ENGS 2,"Integrated Design: Engineering, Architecture, ...",An introduction to the integrated design of st...,https://engineering.dartmouth.edu/courses/unde...
2,ENGS 3,Materials: The Substance of Civilization,"With the exception of ideas and emotions, mate...",https://engineering.dartmouth.edu/courses/unde...
3,ENGS 3.10,Elementary Oceanography,Oceanography is one of the studies in which na...,https://engineering.dartmouth.edu/courses/unde...
4,ENGS 4,Technology of Cyberspace,This course will cover some basic concepts und...,https://engineering.dartmouth.edu/courses/unde...
...,...,...,...,...
264,ENGG 419,Deep Learning,Although there are many approaches to machine ...,https://engineering.dartmouth.edu/courses/grad...
265,ENGG 462,Embedded Systems,This is a graduate-level course covering the d...,https://engineering.dartmouth.edu/courses/grad...
266,ENGG 463,Advanced FPGA Design,This graduate-level course builds on foundatio...,https://engineering.dartmouth.edu/courses/grad...
267,ENGG 499,Smart Sensors,Design methodologies of mobile sensors and sys...,https://engineering.dartmouth.edu/courses/grad...
268,ENGG 700,Responsible & Ethical Conduct of Research,NaN,https://engineering.dartmouth.edu/courses/grad...

In [3]:
# tuck_school_courses_total.csv
import pandas as pd
df_loaded_tuck = pd.read_csv('tuck_school_courses_total.csv', header = None, names = ['course_code','course_name', 'course_description', 'course_url'])

In [5]:
# schools of arts and sciences - 'arts_science_grad_courses.csv'
import pandas as pd
df_loaded_arts_sciences = pd.read_csv('arts_science_grad_courses.csv', header = None, names = ['course_code','course_name', 'course_description', 'course_url'])

In [ ]:
# Geisel School of Medicine courses - 'med_courses.csv'

import pandas as pd
df_loaded_med_courses= pd.read_csv('med_courses.csv', names = ['course_code','course_name', 'course_description', 'course_url'], header = None)

In [16]:
# set all above courses data frame together

df_loaded_courses= pd.concat([df_loaded_engineering, df_loaded_tuck, df_loaded_arts_sciences, df_loaded_med_courses], ignore_index = True)

In [17]:
len(df_loaded_courses)

974

In [18]:
df_loaded_courses

,course_code,course_name,course_description,course_url
0,ENGS 1.01,Mathematical Concepts in Engineering,This course introduces prospective engineering...,https://engineering.dartmouth.edu/courses/unde...
1,ENGS 2,"Integrated Design: Engineering, Architecture, ...",An introduction to the integrated design of st...,https://engineering.dartmouth.edu/courses/unde...
2,ENGS 3,Materials: The Substance of Civilization,"With the exception of ideas and emotions, mate...",https://engineering.dartmouth.edu/courses/unde...
3,ENGS 3.10,Elementary Oceanography,Oceanography is one of the studies in which na...,https://engineering.dartmouth.edu/courses/unde...
4,ENGS 4,Technology of Cyberspace,This course will cover some basic concepts und...,https://engineering.dartmouth.edu/courses/unde...
...,...,...,...,...
969,NaN,"HCDS MOC Managing People, Organizations and Ch...","Today, many organizations confront situations ...",https://dartmouth.smartcatalogiq.com/en/curren...
970,NaN,HCDS PHPC Population Health and Preventive Care,"In this course, students will learn about the ...",https://dartmouth.smartcatalogiq.com/en/curren...
971,NaN,HCDS PLS Personal Leadership,The focus of the course is concrete — building...,https://dartmouth.smartcatalogiq.com/en/curren...
972,NaN,HCDS SPE Specialty Topics in Health Care Delivery,Integrative Experiences in Health Care Deliver...,https://dartmouth.smartcatalogiq.com/en/curren...
973,NaN,HCDS STRAT Strategy for Health Care Organizations,This course focuses on the effective formulati...,https://dartmouth.smartcatalogiq.com/en/curren...

In [19]:
df_loaded_courses = df_loaded_courses.to_csv('all_courses.csv',index=False, header=True)